### ISSUE TITLE
可否加上秒

### ISSUE THREAD

**Issue by shenshangjimiaoZG** [DreamOfXM/XMDatePicker#1]
现在年月日时分都有了，可否加上秒？

**Comment by DreamOfXM** [comment]
当时设计的时候以为秒没有用，有过有需求的话，可以加上，但是我白天比较忙，只能晚上搞,如果方便的话，你把你的具体需求说一下，我晚上添上

**Comment by DreamOfXM** [comment]
@huangping35 已添加秒功能,时间仓促，不知道能否满足你的需求……
